disciplinas = [
    'Administração Financeira -> 80 horas', 
    'Ambiente de Desenvolvimento e Operação - DevOps -> 80 horasAmbiente de Desenvolvimento e Operação - DevOps: 80 horas', 
    'Análise e Modelagem de Sistemas -> 80 horas', 
    'Análise Exploratória de Dados -> 80 horas', 
    'Análise de Viabilidade de Projetos -> 80 horas', 
    'Arquitetura e Projeto de Sistemas -> 80 horas', 
    'Atividades Complementares -> 160 horas', 
    'Cálculo -> 80 horas', 
    'Comportamento Organizacional -> 40 horas', 
    'Comunicação e Expressão  (EAD) -> 80 horas', 
    'Comunicação e Expressão -> 80 horas (EAD)', 
    'Contabilidade Financeira -> 80 horas', 
    'Contabilidade Gerencial -> 80 horas', 
    'Desenvolvimento de Aplicações Distribuídas -> 80 horas', 
    'Design Thinking -> 40 horas', 
    'Direito Aplicado à Administração -> 80 horas', 
    'Engenharia de Requisitos -> 80 horas', 
    'Engenharia de Software: 80 horasEngenharia de Software -> 80 horas', 
    'Estágio supervisionado -> 320 horas', 
    'Estratégia Competitiva e Corporativa -> 80 horas', 
    'Estratégia Organizacional -> 80 horas', 
    'Estrutura de Dados -> 80 horas', 
    'Finanças Corporativas e Mercado de Capitais -> 80 horas', 
    'Fundamentos da Administração -> 80 horas', 
    'Fundamentos de Banco de Dados -> 80 horas', 
    'Gestão da Cadeia de Suprimentos -> 80 horas', 
    'Gestão de Custos -> 80 horas', 
    'Gestão de Marketing -> 80 horas', 
    'Gestão de Operações -> 80 horas', 
    'Gestão de Projetos de Inovação -> 80 horas', 
    'Gestão de Projetos e Programas -> 80 horas', 
    'Gestão de Projetos - Optativa -> 40 horas', 
    'Gestão de Qualidade -> 80 horas', 
    'Gestão Estratégica de Pessoas -> 80 horas', 
    'Governança Corporativa -> 80 horas', 
    'Inteligência de Negócios -> 80 horas', 
    'Interface Homem-Computador -> 40 horas (EAD)', 
    'Introdução à Internet das Coisas -> IoT: 80 horas', 
    'Jogos de Estratégias -> 80 horas', 
    'Língua Brasileira de Sinais - Optativa -> 40 horas', 
    'Linguagem de Programação I -> 80 horas', 
    'Linguagem de Programação II: 80 horas', 
    'Linguagem de Programação II -> 80 horas', 
    'Linguagem SQL: 80 horasLinguagem SQL -> 80 horas', 
    'Lógica de Programação -> 80 horas', 
    'Macroeconomia -> 80 horas', 
    'Marketing Avançado -> 80 horas', 
    'Matemática Aplicada -> 80 horas', 
    'Matemática Aplicada -> 80 horas', 
    'Matemática Financeira -> 40 horas', 
    'Microeconomia -> 80 horas', 
    'Modelagem de Processos de Negócio -> 80 horas', 
    'Modelos de Negócio e Empreendedorismo -> 80 horas', 
    'Negócios Internacionais -> 80 horas', 
    'Oficina Projeto Empresa 1 - OPE1 -> 120 horas', 
    'Optativa (Sociedade e Sustentabilidade / Língua Brasileira de Sinais - LIBRAS) -> 80 horas', 
    'Pensamento Crítico e Ética -> 80 horas', 
    'Raciocínio Analítico -> 80 horas', 
    'Responsabilidade Social Corporativo -> 40 horas', 
    'Sistemas Integrados de Gestão -> 80 horas', 
    'Sociedade e Sustentabilidade -> 40 horas', 
    'Sociologia e Política -> 80 horas', 
    'Startup e Inovação -> 80 horas', 
    'Tecnologia Web: 80 horasTecnologia Web -> 80 horas', 
    'Tomada de Decisão e Negociação -> 80 horas', 
    'Trabalho de Conclusão de Curso 1 - TCC1 -> 80 horas', 
    'Trabalho de Conclusão de Curso 2 - TCC2 -> 80 horas', 
    'Legislação e Ética -> 40 horas (EAD)', 
    'Oficina Projeto Empresa 2 - OPE2 -> 120 horas (40 EAD)', 
    'Qualidade de Software -> 80 horas', 
    'Comunicação e Expressão -> 80 horas (EAD)', 
    'Fundamentos de Banco de Dados -> 80 horas', 
    'Introdução à Internet das Coisas -> IoT: 80 horas', 
    'Linguagem de Programação I -> 80 horas', 
    'Lógica de Programação -> 80 horas', 
    'Matemática Aplicada -> 80 horas', 
    'Ambiente de Desenvolvimento e Operação - DevOps -> 80 horasAmbiente de Desenvolvimento e Operação - DevOps: 80 horas', 
    'Engenharia de Software: 80 horasEngenharia de Software -> 80 horas', 
    'Gestão de Projetos - Optativa -> 40 horas', 
    'Língua Brasileira de Sinais - Optativa -> 40 horas', 
    'Linguagem de Programação II: 80 horasLinguagem de Programação II -> 80 horas', 
    'Linguagem SQL: 80 horasLinguagem SQL -> 80 horas', 
    'Sociedade e Sustentabilidade -> 40 horas', 
    'Tecnologia Web: 80 horasTecnologia Web -> 80 horas', 
    'Análise e Modelagem de Sistemas -> 80 horas', 
    'Desenvolvimento de Aplicações Distribuídas -> 80 horas', 
    'Estrutura de Dados -> 80 horas', 
    'Interface Homem-Computador -> 40 horas (EAD)', 
    'Engenharia de Requisitos -> 80 horas', 
    'Oficina Projeto Empresa 1 - OPE1 -> 120 horas', 
    'Arquitetura e Projeto de Sistemas -> 80 horas', 
    'Desenvolvimento para Internet das Coisas - IoT -> 80 horas', 
    'Legislação e Ética -> 40 horas (EAD)', 
    'Oficina Projeto Empresa 2 - OPE2 -> 120 horas (40 EAD)', 
    'Qualidade de Software -> 80 horas', 
    'Circuitos Digitais e Eletrônicos -> 80 horas', 
    'Comunicação e Expressão -> 80 horas', 
    'Instrodução à Internet das Coisas -IOT -> 80 Horas', 
    'Linguagem de Programação I -> 80 horas', 
    'Lógica de Programação -> 80 horas', 
    'Matemática para Engenharia -> 80 horas', 
    'Ambiente de Desenvolvimento e Operação - DevOps -> 80 horas', 
    'Banco de Dados -> 80 horas', 
    'Conceitos e Aplicações de Cálculo -> 80 horas', 
    'Engenharia de Software -> 80 horas', 
    'Língua Brasileira de Sinais - LIBRAS (Optativa) -> 40 horas', 
    'Linguagem de Programação II -> 80 horas', 
    'Sociedade e Sustentabilidade (Optativa) -> 40 horas', 
    'Análise e Modelagem de Sistemas -> 80 horas', 
    'Ciências do Ambiente -> 40 horas', 
    'Desenvolvimento de Aplicações Distribuídas -> 80 horas', 
    'Estrutura de Dados -> 80 horas', 
    'Engenharia de Requisitos -> 80 horas', 
    'Modelagem e Simulação de Sistemas Físicos -> 80 horas', 
    'Circuitos Elétricos: 80 horas', 
    'Desenvolvimento para Dispositivos Móveis: 80 horas', 
    'Desenvolvimento para Internet das Coisas - IoT: 80 horas', 
    'Eletricidade e Magnetismo Aplicados: 80 horas', 
    'Matemática Discreta: 80 horas', 
    'Otimização de Sistemas Lineares', 
    'Análise Exploratória de Dado', 
    'Análise Numérica -', 
    'Arquitetura de Computadores e Sistemas Operacionais -> 80 horas', 
    'Eletrônica Analógica e Digital -> 80 horas', 
    'Linguagens Formais e Autômatos -> 80 horas', 
    'Processamento Digital de Sinais -> 80 horas', 
    'Análise de Viabilidade de Projetos -> 80 horas', 
    'Compiladores -> 80 horas', 
    'Controle e Automação -> 80 horas', 
    'Gestão Ágil de Projetos -> 40 horas', 
    'Inteligência Artificial -> 80 horas', 
    'Sistemas Distribuídos e Cloud Computing -> 80 horas', 
    'Economia para Engenharia -> 40 horas', 
    'Robôs Móveis Inteligentes -> 80 horas', 
    'Segurança Cibernética -> 80 horas', 
    'Startup e Inovação -> 80 horas', 
    'Trabalho de Conclusão de Curso 1 - TCC1 -> 80 horas', 
    'UX e Design Thinking -> 80 horas', 
    'Indústria 4.0 -> 80 horas', 
    'Legislação e Ética -> 40 horas', 
    'Projeto de Sistemas Embarcados -> 80 horas', 
    'Sistemas Tolerantes a Falhas -> 80 horas', 
    'Tópicos Especiais em Tendências Tecnológicas -> 80 horas', 
    'Trabalho de Conclusão de Curso 2 - TCC2 -> 80 horas', 
    'Circuitos Digitais e Eletrônicos -> 80 horas', 
    'Comunicação e Expressão -> 80 horas', 
    'Instrodução à Internet das Coisas -IOT -> 80 Horas', 
    'Linguagem de Programação I -> 80 horas', 
    'Lógica de Programação -> 80 horas', 
    'Matemática para Engenharia -> 80 horas', 
    'Ambiente de Desenvolvimento e Operação - DevOps -> 80 horas', 
    'Análise Exploratória de Dados -> 80 horas', 
    'Engenharia de Software: 80 horasEngenharia de Software -> 80 horas', 
    'Gestão de Projetos - Optativa -> 40 horas', 
    'Gestão Estratégica de Pessoa -> 80 horas', 
    'Sistemas Integrados de Gestão -> 80 horas', 
    'Optativa (Sociedade e Sustentabilidade / Língua Brasileira de Sinais - LIBRAS) -> 40 horas', 
    'Análise de Viabilidade de Projetos -> 80 horas', 
    'Inteligência de Negócios -> 80 horas', 
    'Legislação e Ética -> 40 horas (EAD)', 
    'Modelagem de Processos de Negócio -> 80 horas', 
    'Qualidade de Software -> 80 horas', 
    'Oficina Projeto Empresa 1 - OPE1 -> 120 horas', 
    'Gestão da Qualidade -> 80 horas', 
    'Gestão da Segurança de Informação -> 80 horas (EAD)', 
    'Gestão de Infraestrutura de TI -> 80 horas', 
    'Gestão Estratégica de TI -> 80 horas', 
    'Governança de TI -> 80 horas', 
    'Oficina Projeto Empresa 2 - OPE2 -> 80 horas', 
    'Arte 2D para Jogos Digitais -> 80 horas', 
    'Desenho e Concept Art para Jogos -> 80 horas', 
    'Design de Jogos I -> 80 horas', 
    'Empreendedorismo -> 80 horas', 
    'Introdução à Programação para Jogos Digitais -> 80 horas', 
    'Introdução aos Jogos Digitais -> 80 horas', 
    'Optativa (Sociedade e Sustentabilidade / Língua Brasileira de Sinais - LIBRAS) -> 40 horas', 
    'Ambiente de Desenvolvimento de Jogos Digitais -> 80 horas', 
    'Arte 3D para Jogos Digitais -> 80 horas', 
    'Design de Jogos II -> 40 horas', 
    'Programação para Jogos Digitais I -> 40 horas', 
    'Processo de Produção de Jogos Digitais (EAD) -> 80 horas', 
    'Game Level Design -> 80 horas', 
    'Design de Personagens para Jogos Digitais -> 80 horas', 
    'Jogos Digitais para Web -> 80 horas', 
    'Interfaces para Jogos Digitais (EAD) -> 80 horas', 
    'Oficina Projeto Empresa 1 - OPE1 -> 120 horas', 
    'Programação para Jogos Digitais II -> 80 horas', 
    'Roteirização e Storyboard para Jogos Digitais -> 80 horas', 
    'Animação, Áudio e Vídeo para Jogos Digitais -> 80 horas', 
    'Estudos Complementares em Jogos Digitais -> 80 horas', 
    'Jogos Digitais para Dispositivos Móveis -> 80 horas', 
    'Oficina Projeto Empresa 2 - OPE2 -> 120 horas)', 
    'Marketing para Jogos Digitais -> 80 horas', 
    'Qualidade e Testes para Jogos Digitais -> 80 horas', 
    'Administração de Redes e Sistemas -> 80 horas', 
    'Arquitetura de Redes de Computadores -> 80 horas', 
    'Cabeamento Estruturado -> 80 horas', 
    'Comunicação e Expressão (EAD) -> 80 horas', 
    'Fundamentos de Sistemas Operacionais -> 40 horas', 
    'Introdução à Internet das Coisas - IoT -> 80 horas', 
    'Programação para Redes -> 80 horas', 
    'Administração de Redes e Sistemas Operacionais Livres -> 80 hora', 
    'Ambiente de Desenvolvimento e Operação - DevOps -> 80 horas', 
    'Gestão de Projetos (EAD) -> 40 horas', 
    'Gestão de TI (EAD) -> 40 horas', 
    'Oficina Projeto Empresa 1 - OPE1 -> 40 horas', 
    'Redes de Longa Distância -> 40 horas', 
    'Routing -> 80 horas', 
    'Segurança em Redes e Infraestrutura -> 80 horas', 
    'Comunicação de Dados -> 40 horas', 
    'Diagnóstico e Gerenciamento de Redes -> 80 horas', 
    'Legislação e Ética -> 40 horas (EAD)', 
    'Oficina Projeto Empresa 2 - OPE2 -> 40 horas', 
    'Optativa (Sociedade e Sustentabilidade / Língua Brasileira de Sinais - LIBRAS) -> 40 horas (EAD)', 
    'Redes Convergentes -> 80 horas', 
    'Segurança em Sistemas -> 80 horas', 
    'Switching -> 80 horas', 
    'Computação em Nuvem -> 80 horas', 
    'Comunicações Móveis -> 80 horas', 
    'Auditoria e Controle de TI -> 40 horas (EAD)', 
    'Oficina Projeto Empresa 3 - OPE3 -> 120 horas (40 EAD)', 
    'Redes IPV6 -> 40 horas', 
    'Serviços de Redes de Computadores -> 80 horas', 
    'Tópicos Especiais em Redes de Computadores -> 40 horas', 
    'Comunicação e Expressão -> 80 horas (EAD)', 
    'Fundamentos de Banco de Dados -> 80 horas', 
    'Introdução à Internet das Coisas -> IoT: 80 horas', 
    'Linguagem de Programação I -> 80 horas', 
    'Lógica de Programação -> 80 horas', 
    'Matemática Aplicada -> 80 horas', 
    'Ambiente de Desenvolvimento e Operação - DevOps -> 80 horasAmbiente de Desenvolvimento e Operação - DevOps: 80 horas', 
    'Engenharia de Software: 80 horasEngenharia de Software -> 80 horas', 
    'Gestão de Projetos: 40 horas (EAD)Gestão de Projetos -> 40 horas (EAD)', 
    'Linguagem de Programação II: 80 horasLinguagem de Programação II -> 80 horas', 
    'Linguagem SQL: 80 horasLinguagem SQL -> 80 horas', 
    'Optativa (Sociedade e Sustentabilidade / Língua Brasileira de Sinais - LIBRAS) -> 40 horas (EAD)Optativa (Sociedade e Sustentabilidade / Língua Brasileira de Sinais - LIBRAS): 40 horas (EAD)', 
    'Tecnologia Web: 80 horasTecnologia Web -> 80 horas', 
    'Análise e Modelagem de Sistemas: 80 horas', 
    'Desenvolvimento de Aplicações Distribuídas: 80 horas', 
    'Estrutura de Dados: 80 horas', 
    'Interface Homem-Computador: 40 horas (EAD)', 
    'Engenharia de Requisitos: 80 horas', 
    'Oficina Projeto Empresa 1 - OPE1: 120 horas (40 EAD', 
    'Arquitetura e Projeto de Sistemas -> 80 horas', 
    'Desenvolvimento para Internet das Coisas - IoT -> 80 horas', 
    'Legislação e Ética -> 40 horas (EAD)', 
    'Oficina Projeto Empresa 2 - OPE2 -> 120 horas (40 EAD)', 
    'Qualidade de Software -> 80 horas', 
    'Business Agility -> 80 horas', 
    'Desenvolvimento de Sistemas de Informação -> 80 horas', 
    'Startup e Inovação -> 80 horas', 
    'Teoria da Computação -> 80 horas', 
    'Análise de Viabilidade de Projetos -> 80 horas', 
    'Análise Exploratória de Dados -> 80 horas', 
    'Gestão de Projetos de Inovação -> 80 horas', 
    'Integração e Desenvolvimento de Sistemas -> 80 horas', 
    'Business Intelligence -> 80 horas', 
    'Segurança e Auditoria de Sistemas -> 80 horas', 
    'Gestão de Infraestrutura de TI -> 80 horas', 
    'Trabalho de Conclusão de Curso 1 - TCC1 -> 80 horas', 
    'Computação Cognitiva -> 80 horas', 
    'Governança de TI -> 80 horas', 
    'Sistemas Integrados de Gestão -> 80 horas', 
    'Trabalho de Conclusão de Curso 2 - TCC2 -> 80 horas']

disciplinas_ordenadas = sorted(disciplinas)

print(disciplinas_ordenadas)
